name: Deploy to Vercel

on:
  push:
    branches:
      - main  # only merge/pushes to main trigger this

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 22.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0

      # - name: Install dependencies
      #   run: yarn install --frozen-lockfile

      # - name: Build app
      #   env:
      #     NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      #     CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      #     NEXT_PUBLIC_CLERK_SIGN_IN_URL: 
      #     NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-UP
      #     NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=/
      #     NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=/
      #     CLERK_WEBHOOK_SIGNING_SECRET=whsec_DCOGql0XX4kf/pYKxxhTwAIOvRUH1Y5r
      #     DATABASE_URL=postgresql://neondb_owner:npg_6csjQlUETMm1@ep-royal-cell-adsvinpn-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      #     UPSTASH_REDIS_REST_URL="https://aware-kangaroo-44680.upstash.io"
      #     UPSTASH_REDIS_REST_TOKEN="Aa6IAAIncDExZTg3NzlhNmE5ZDI0YzMzOTdhNWM1M2JiOTM3MTM5ZnAxNDQ2ODA"

        # run: yarn build

      - name: Install Vercel CLI
        run: yarn global add vercel@latest

      - name: Pull Vercel project config
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
